#!/bin/sh
RED=''
GREEN=''
NC='' # No Color
if [ $# -ne 1 ] ;then
    echo "Usage : run_test [file size]"
    exit
fi

# build
make
# generate test file
dd if=/dev/urandom of=test_in bs=$1 count=1 >> /dev/null 2>&1

# sigalrm
# udp dump
#killall tcpdump >> /dev/null 2>&1
#tcpdump -i lo -n udp port 5000 -w sigalrm.pcap >> /dev/null 2>&1 &
# run receiver in background
killall receiver_sigalrm >> /dev/null 2>&1
./receiver_sigalrm test_sigalrm 5000 > /dev/null & 
# run sender
time ./sender_sigalrm test_in localhost 5000 > /dev/null
# diff check
echo "Difference Check.."
diff test_in test_sigalrm
if [ $? -ne 0 ];then
    echo "${RED}***FAIL***${NC}"
else
#FILESIZE=$(stat -c%s "./sigalrm.pcap")
#SIZE=$(numfmt --to=iec-i --suffix=B --format="%.5f" $FILESIZE) 
#echo "Size of sigalrm.pcap = $SIZE."
    echo "${GREEN}***PASS***${NC}"
fi
sleep 1
# select
# udp dump
#killall tcpdump >> /dev/null 2>&1
#tcpdump -i lo -n udp port 5000 -w select.pcap >> /dev/null 2>&1 &
# run receiver in background
killall receiver_select >> /dev/null 2>&1
./receiver_select test_select 5000 > /dev/null &
# run sender
time ./sender_select test_in localhost 5000 > /dev/null
# diff check
echo "Difference Check.."
diff test_in test_select
if [ $? -ne 0 ];then
    echo "${RED}***FAIL***${NC}"
else
#FILESIZE=$(stat -c%s "./select.pcap")
#SIZE=$(numfmt --to=iec-i --suffix=B --format="%.5f" $FILESIZE) 
#echo "Size of select.pcap = $SIZE."
    echo "${GREEN}***PASS***${NC}"
fi
sleep 1
# sockopt
# udp dump
#killall tcpdump >> /dev/null 2>&1
#tcpdump -i lo -n udp port 5000 -w sockopt.pcap >> /dev/null 2>&1 &
# run receiver in background
killall receiver_sockopt >> /dev/null 2>&1
./receiver_sockopt test_sockopt 5000 > /dev/null &
# run sender
time ./sender_sockopt test_in localhost 5000 >> /dev/null |grep real
# diff check
echo "Difference Check.."
diff test_in test_sockopt
if [ $? -ne 0 ];then
    echo "${RED}***FAIL***${NC}"
else
#FILESIZE=$(stat -c%s "./sockopt.pcap")
#SIZE=$(numfmt --to=iec-i --suffix=B --format="%.5f" $FILESIZE) 
#echo "Size of sockopt.pcap = $SIZE ."
    echo "${GREEN}***PASS***${NC}"
fi
killall tcpdump >> /dev/null 2>&1

